package constant::exported;
use strict;
use warnings;
our $VERSION = '1.0';

sub import ($$$) {
  my ($class, $name, $value) = @_;
  my $package = caller;
  no strict 'refs';
  *{$package . '::' . $name} = sub () { $value };
  push @{$package . '::EXPORT'}, $name;
} # import

1;

=head1 LICENSE

Copyright 2010 Wakaba <w@suika.fam.cx>.

This library and the library generated by it is free software; you can
redistribute them and/or modify them under the same terms as Perl
itself.

=cut
