package test::constant::exported;
use strict;
use warnings;
use Path::Class;
use lib file (__FILE__)->dir->parent->subdir ('lib')->stringify;
use base qw(Test::Class);
use Test::More;

{
  package test::constant::exported::package1;
  use constant::exported ABC => 1;
  use constant::exported XYZ => rand;
  use Exporter::Lite;
  BEGIN { $INC{'test/constant/exported/package1.pm'} = 1 };
}

sub _used_constants : Test(5) {
  {
    package test::constant::exported::package1;

    use Test::More;
    is ABC, 1;
    like XYZ, qr/^[0-9.]+$/;
    is XYZ, XYZ;

    local *ABC = sub { 2 };
    local *XYZ = sub { 'abc' };

    is ABC, 1;
    like XYZ, qr/^[0-9.]+$/;
  }
} # _used_constants

sub _exported_constants : Test(5) {
  {
    package test::constant::exported::package2;
    use test::constant::exported::package1;

    use Test::More;
    is ABC, 1;
    like XYZ, qr/^[0-9.]+$/;
    is XYZ, XYZ;

    local *ABC = sub { 2 };
    local *XYZ = sub { 'abc' };

    is ABC, 1;
    like XYZ, qr/^[0-9.]+$/;
  }
} # _exported_constants

__PACKAGE__->runtests;

1;

=head1 LICENSE

Copyright 2010 Wakaba <w@suika.fam.cx>.

This library and the library generated by it is free software; you can
redistribute them and/or modify them under the same terms as Perl
itself.

=cut
